version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: donna_postgres
    environment:
      POSTGRES_USER: donna
      POSTGRES_PASSWORD: donna
      POSTGRES_DB: donna
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.8
    container_name: donna_redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
    ports:
      - "9092:9092"   # Kafka API
      - "9644:9644"   # Admin API
    environment:
      - REDPANDA_ENVIRONMENT=dev
