services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: donna_postgres
    environment:
      POSTGRES_USER: donna
      POSTGRES_PASSWORD: donna
      POSTGRES_DB: donna
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: donna_redpanda
    shm_size: "1gb"
    
    # 🌟 FIX: ulimits correctly formatted as a mapping
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 8192
      
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      
    # 🌟 FIX/IMPROVEMENT: Healthcheck added to confirm broker readiness
    healthcheck:
      test: ["CMD", "/usr/bin/rpk", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 10
      
    # 🌟 FIX: ports correctly aligned with 'healthcheck' and 'ulimits'
    ports: 
      - "9094:19092"
      - "9644:9644"
      
    environment:
      - REDPANDA_ENVIRONMENT=dev

  donna:
    build:
      context: ../Donna
    container_name: donna_orchestrator
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: donna-orchestrator
      CASEEVENT_TOPIC: events.caseevent
      TO_CM_TOPIC: tasks.case_manager
      FROM_CM_TOPIC: results.case_manager
      TO_PL_TOPIC: tasks.paralegal
      FROM_PL_TOPIC: results.paralegal
      PRECEDENTS_DIR: /precedence
      # Recommended: Add for unbuffered Python output
      PYTHONUNBUFFERED: 1 
      
    volumes:
      - ./common-contracts:/app/common-contracts:ro
      - ./precedence:/precedence
      
    # 🌟 FIX: Dependency waits for Redpanda to be healthy, preventing NoBrokersAvailable crash
    depends_on:
      redpanda:
        condition: service_healthy